name: Build
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/notAperson55/fluent-ui-vscode.git
      - run: cd fluent-ui-vscode
      - run: npm install -g vsce
      - run: vsce package
      - run: ls
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
